# Using `fpl_data.transform` module

In [1]:
import pandas as pd
from fpl_data_loader.transform import FplDataTransformer

pd.set_option("display.max_columns", None)

Load and transform data

In [2]:
data = FplDataTransformer()

Getting data from API
...
DONE!

## Players

In [3]:
# get a list of all players as a dataframe
data.players_df.sort_values("total_points", ascending=False)

,chance_of_playing_next_round,chance_of_playing_this_round,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,dreamteam_count,ep_next,ep_this,event_points,first_name,form,in_dreamteam,news,news_added,price,points_per_game,last_name,selected_by_percent,special,total_points,transfers_in,transfers_in_event,transfers_out,transfers_out_event,value_form,value_season,short_name,minutes_played,goals_scored,assists,clean_sheets,goals_conceded,own_goals,penalties_saved,penalties_missed,yellow_cards,red_cards,saves,bonus,bps,influence,creativity,threat,ict_index,clearances_blocks_interceptions,recoveries,tackles,defensive_contribution,starts,expected_goals,expected_assists,expected_goal_involvements,expected_goals_conceded,influence_rank,influence_rank_type,creativity_rank,creativity_rank_type,threat_rank,threat_rank_type,ict_index_rank,ict_index_rank_type,corners_and_indirect_freekicks_order,corners_and_indirect_freekicks_text,direct_freekicks_order,direct_freekicks_text,penalties_order,penalties_text,expected_goals_per_90,saves_per_90,expected_assists_per_90,expected_goal_involvements_per_90,expected_goals_conceded_per_90,goals_conceded_per_90,now_cost_rank,now_cost_rank_type,form_rank,form_rank_type,points_per_game_rank,points_per_game_rank_type,selected_rank,selected_rank_type,starts_per_90,clean_sheets_per_90,defensive_contribution_per_90,team,team_name_long,position,position_name_long,goal_involvements,expected_points,total_points_per_90,goals_scored_per_90,assists_per_90,goal_involvements_per_90,expected_points_per_90,bps_per_90,influence_per_90,creativity_per_90,threat_per_90,ict_index_per_90
player_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
226,NaN,NaN,0,0,0,0,1,9.5,9.5,13,Trevoh,9.0,True,,None,5.0,9.0,Chalobah,4.3,False,27,345492,47584,56624,2002,1.8,5.4,Chalobah,248,1,1,2,1,0,0,0,0,0,0,2,95,91.0,14.9,54.0,16.0,18,9,7,25,3,0.5,0.2,0.8,2.0,14,2,159,48,30,4,27,2,NaN,,NaN,,NaN,,0.2,0.0,0.1,0.3,0.7,0.4,244,38,1,1,6,5,84,33,1.1,0.7,9.1,CHE,Chelsea,DEF,Defender,2,7.2,9.8,0.4,0.4,0.7,2.6,34.5,33.0,5.4,19.6,5.8
7,NaN,NaN,0,0,1,-1,2,9.2,8.2,0,Riccardo,8.7,True,,None,5.6,13.0,Calafiori,8.9,False,26,738321,33451,97492,2963,1.6,4.6,Calafiori,134,1,2,2,0,0,0,0,1,0,0,3,71,74.2,23.5,57.0,15.4,4,6,1,5,2,1.3,0.0,1.3,1.0,28,8,107,24,27,3,30,3,NaN,,NaN,,NaN,,0.9,0.0,0.0,0.9,0.7,0.0,120,12,2,2,1,1,47,17,1.3,1.3,3.4,ARS,Arsenal,DEF,Defender,3,11.8,17.5,0.7,1.3,2.0,7.9,47.7,49.8,15.8,38.3,10.3
249,NaN,NaN,0,0,1,-1,2,9.2,9.2,9,João Pedro,8.7,True,,None,7.6,8.7,Junqueira de Jesus,61.0,False,26,1260640,101044,508868,4075,1.1,3.4,João Pedro,252,2,2,2,1,0,0,0,0,0,0,6,107,125.6,50.0,109.0,28.2,6,8,2,16,3,1.4,0.2,1.5,2.4,1,1,38,2,2,2,3,1,NaN,,NaN,,NaN,,0.5,0.0,0.0,0.5,0.8,0.4,21,8,3,1,7,2,1,1,1.1,0.7,5.7,CHE,Chelsea,FWD,Forward,4,7.8,9.3,0.7,0.7,1.4,2.8,38.2,44.9,17.9,38.9,10.1
237,NaN,NaN,0,0,0,0,1,8.8,8.8,12,Enzo,8.3,True,,None,6.5,8.3,Fernández,6.1,False,25,309693,96076,98583,2825,1.3,3.8,Enzo,258,2,2,2,1,0,0,0,0,0,0,1,82,97.4,65.7,65.0,22.8,3,6,2,11,3,1.8,0.4,2.2,2.4,12,8,21,19,19,11,7,5,4.0,,3.0,,4.0,,0.6,0.0,0.1,0.8,0.8,0.4,60,42,5,1,10,2,70,25,1.0,0.7,3.8,CHE,Chelsea,MID,Midfielder,4,12.5,8.7,0.7,0.7,1.4,4.4,28.6,34.0,22.9,22.7,8.0
72,NaN,NaN,0,0,0,0,1,8.3,8.3,14,Marcos,8.3,True,,None,4.5,8.3,Senesi Barón,2.2,False,25,176573,53121,40576,1203,1.8,5.6,Senesi,270,0,1,2,4,0,0,0,0,0,0,4,73,87.8,26.2,10.0,12.4,36,12,6,42,3,0.1,0.1,0.2,2.8,16,4,95,21,167,37,47,8,NaN,,NaN,,NaN,,0.0,0.0,0.0,0.1,1.0,1.3,407,93,4,3,9,6,118,49,1.0,0.7,14.0,BOU,Bournemouth,DEF,Defender,1,4.0,8.3,0.0,0.3,0.3,1.3,24.3,29.3,8.7,3.3,4.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
411,NaN,NaN,0,0,-1,1,0,0.5,0.5,0,Nico,0.0,False,,None,4.9,0.0,O'Reilly,0.1,False,0,2255,76,6823,188,0.0,0.0,O’Reilly,24,0,0,0,0,0,0,0,1,0,0,0,-2,0.0,5.0,0.0,0.5,0,0,0,0,0,0.0,0.0,0.0,0.2,624,227,228,67,591,215,330,111,NaN,,NaN,,NaN,,0.0,0.0,0.0,0.0,0.8,0.0,350,62,626,224,626,224,433,165,0.0,0.0,0.0,MCI,Man City,DEF,Defender,0,5.3,0.0,0.0,0.0,0.0,20.0,-7.5,0.0,18.8,0.0,1.9
331,NaN,NaN,0,0,-1,1,0,0.5,-0.5,0,Tom,0.0,False,,None,4.9,0.0,Cairney,0.0,False,0,179,12,1233,62,0.0,0.0,Cairney,24,0,0,0,0,0,0,0,1,0,0,0,-3,0.0,0.4,0.0,0.0,0,2,0,2,0,0.0,0.0,0.0,0.4,600,244,315,164,564,236,603,246,NaN,,2.0,,NaN,,0.0,0.0,0.0,0.0,1.6,0.0,317,200,603,249,603,249,617,256,0.0,0.0,7.5,FUL,Fulham,MID,Midfielder,0,2.7,0.0,0.0,0.0,0.0,10.1,-11.2,0.0,1.5,0.0,0.0
672,NaN,NaN,0,0,-1,1,0,0.5,0.5,0,Jorrel,0.0,False,,None,4.9,0.0,Hato,0.3,False,0,3983,79,15367,834,0.0,0.0,Hato,21,0,0,0,0,0,0,0,1,0,0,0,-2,1.2,1.0,0.0,0.2,1,1,0,1,0,0.0,0.0,0.0,0.4,332,120,299,106,596,216,347,123,NaN,,NaN,,NaN,,0.0,0.0,0.0,0.0,1.9,0.0,359,63,631,225,631,225,329,121,0.0,0.0,4.3,CHE,Chelsea,DEF,Defender,0,4.8,0.0,0.0,0.0,0.0,20.5,-8.6,5.1,4.3,0.0,0.9
632,NaN,NaN,0,0,0,0,0,-0.5,0.0,0,Matt,0.0,False,,None,4.5,0.0,Doherty,0.2,False,0,1734,27,4475,245,0.0,0.0,Doherty,180,0,0,0,5,0,0,0,2,0,0,0,4,29.0,7.7,0.0,3.7,8,8,6,14,2,0.0,0.0,0.0,3.8,153,68,204,61,444,189,225,76,NaN,,NaN,,NaN,,0.0,0.0,0.0,0.0,1.9,2.5,375,70,497,203,497,203,380,139,1.0,0.0,7.0,WOL,Wolves,DEF,Defender,0,2.9,0.0,0.0,0.0,0.0,1.5,2.0,14.5,3.8,0.0,1.8
148,NaN,NaN,0,0,-1,1,0,0.0,-0.5,0,Ferdi,0.0,False,,None,4.4,0.0,Kadıoğlu,0.2,False,0,1724,52,7225,204,0.0,0.0,F.Kadıoğlu,44,0,0,0,1,0,0,0,2,0,0,0,-6,0.0,3.5,0.0,0.3,2,2,0,2,0,0.0,0.0,0.0,0.6,472,198,246,76,421,178,340,118,NaN,,NaN,,NaN,,0.0,0.0,0.0,0.0,1.3,2.0,555,138,478,195,478,195,405,152,0.0,0.0,4.1,BHA,Brighton,DEF,Defender,0,4.4,0.0,0.0,0.0,0.0,9.1,-12.3,0.0,7.2,0.0,0.6

## Player summary
The `.get_player_summary()` method can be used to get a player's past or future fixtures

In [4]:
# get the upcoming fixtures for a player
player_fx = data.get_player_summary(355, "fixtures")
player_fx.head()

Fetching
...
DONE!

   team  difficulty
gw
4   FUL           3
5   WOL           3
6   BOU           3
7   TOT           3
8   BUR           2

We can apply some styling to the result above to get a more graphical representation of the upcoming fixtures' difficulty

In [5]:
def style_background_player_fdr(cell_value):
    bg = "background-color:"

    if cell_value == 1:
        return f"{bg} darkgreen;"
    elif cell_value == 2:
        return f"{bg} green;"
    elif cell_value == 3:
        return f"{bg} grey;"
    elif cell_value == 4:
        return f"{bg} orange;"
    elif cell_value == 5:
        return f"{bg} darkred;"
    else:
        return ""


# ToDo: make this part of the package
player_fx.head(10).T.style.map(style_background_player_fdr)

In [6]:
# ToDo: handle case when there are no previous fixtures
player_id = 355
data.get_player_summary(player_id, "history")

Fetching
...
DONE!

,opponent,score,total_points,starts,minutes,goals_scored,assists,expected_goals,expected_assists,expected_goal_involvements,clean_sheets,goals_conceded,expected_goals_conceded,own_goals,penalties_saved,penalties_missed,yellow_cards,red_cards,saves,bonus,bps,influence,creativity,threat,ict_index,net_transfers,selected_by,price
gw,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,EVE (H),1 - 0,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,9774,5.0
2,ARS (A),5 - 0,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,-1633,10276,5.0
3,NEW (H),0 - 0,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,-1561,9575,4.9

## Fixtures
Try to create a fixtures matrix, showing each team's upcoming fixtures and their difficulty

In [7]:
fx = data.get_fixtures_matrix()
fx

,4,5,6,7,8,9,10,11,12
team_home,,,,,,,,,
CHE,BRE (A) 3,MUN (A) 3,BHA (H) 3,LIV (H) 4,NFO (A) 3,SUN (H) 2,TOT (A) 3,WOL (H) 2,BUR (A) 2
LEE,FUL (A) 3,WOL (A) 3,BOU (H) 3,TOT (H) 3,BUR (A) 2,WHU (H) 2,BHA (A) 3,NFO (A) 3,AVL (H) 3
TOT,WHU (A) 2,BHA (A) 3,WOL (H) 2,LEE (A) 2,AVL (H) 3,EVE (A) 3,CHE (H) 3,MUN (H) 3,ARS (A) 4
ARS,NFO (H) 3,MCI (H) 4,NEW (A) 4,WHU (H) 2,FUL (A) 3,CRY (H) 3,BUR (A) 2,SUN (A) 2,TOT (H) 3
WHU,TOT (H) 3,CRY (H) 3,EVE (A) 3,ARS (A) 4,BRE (H) 3,LEE (A) 2,NEW (H) 3,BUR (H) 2,BOU (A) 3
WOL,NEW (A) 4,LEE (H) 2,TOT (A) 3,BHA (H) 3,SUN (A) 2,BUR (H) 2,FUL (A) 3,CHE (A) 4,CRY (H) 3
BOU,BHA (H) 3,NEW (H) 3,LEE (A) 2,FUL (H) 3,CRY (A) 3,NFO (H) 3,MCI (A) 4,AVL (A) 4,WHU (H) 2
BHA,BOU (A) 3,TOT (H) 3,CHE (A) 4,WOL (A) 3,NEW (H) 3,MUN (A) 3,LEE (H) 2,CRY (A) 3,BRE (H) 3
LIV,BUR (A) 2,EVE (H) 2,CRY (A) 3,CHE (A) 4,MUN (H) 3,BRE (A) 3,AVL (H) 3,MCI (A) 4,NFO (H) 3
NEW,WOL (H) 2,BOU (A) 3,ARS (H) 4,NFO (H) 3,BHA (A) 3,FUL (H) 3,WHU (A) 2,BRE (A) 3,MCI (H) 4
FUL,LEE (H) 2,BRE (H) 3,AVL (A) 4,BOU (A) 3,ARS (H) 4,NEW (A) 4,WOL (H) 2,EVE (A) 3,SUN (H) 2
AVL,EVE (A) 3,SUN (A) 2,FUL (H) 3,BUR (H) 2,TOT (A) 3,MCI (H) 4,LIV (A) 5,BOU (H) 3,LEE (A) 2
SUN,CRY (A) 3,AVL (H) 3,NFO (A) 3,MUN (A) 3,WOL (H) 2,CHE (A) 4,EVE (H) 2,ARS (H) 4,FUL (A) 3
CRY,SUN (H) 2,WHU (A) 2,LIV (H) 4,EVE (A) 3,BOU (H) 3,ARS (A) 4,BRE (H) 3,BHA (H) 3,WOL (A) 3
EVE,AVL (H) 3,LIV (A) 5,WHU (H) 2,CRY (H) 3,MCI (A) 4,TOT (H) 3,SUN (A) 2,FUL (H) 3,MUN (A) 3
BRE,CHE (H) 3,FUL (A) 3,MUN (H) 3,MCI (H) 4,WHU (A) 2,LIV (H) 4,CRY (A) 3,NEW (H) 3,BHA (A) 3
MUN,MCI (A) 4,CHE (H) 3,BRE (A) 3,SUN (H) 2,LIV (A) 5,BHA (H) 3,NFO (A) 3,TOT (A) 3,EVE (H) 2
NFO,ARS (A) 4,BUR (A) 2,SUN (H) 2,NEW (A) 4,CHE (H) 3,BOU (A) 3,MUN (H) 3,LEE (H) 2,LIV (A) 5
MCI,MUN (H) 3,ARS (A) 4,BUR (H) 2,BRE (A) 3,EVE (H) 2,AVL (A) 4,BOU (H) 3,LIV (H) 4,NEW (A) 4
BUR,LIV (H) 4,NFO (H) 3,MCI (A) 4,AVL (A) 4,LEE (H) 2,WOL (A) 3,ARS (H) 4,WHU (A) 2,CHE (H) 3

In [8]:
def style_background_team_fdr(cell_value):
    bg = "background-color:"
    team_str = 0

    if cell_value != "":
        team_str = int(cell_value[-1])

    if team_str == 1:
        return f"{bg} darkgreen;"
    elif team_str == 2:
        return f"{bg} green;"
    elif team_str == 3:
        return f"{bg} grey;"
    elif team_str == 4:
        return f"{bg} orange;"
    elif team_str == 5:
        return f"{bg} darkred;"
    else:
        return ""


fx.style.map(style_background_team_fdr)