# Using `fpl_data.transform` module

In [ ]:
import pandas as pd
from fpl_data_loader.transform import FplApiDataTransformed

pd.set_option("display.max_columns", None)

Load and transform data

In [2]:
data = FplApiDataTransformed()

Getting data from API
...
DONE!

## Players

In [3]:
# get a list of all players as a dataframe
data.players_df.sort_values("total_points", ascending=False)

,can_transact,can_select,chance_of_playing_next_round,chance_of_playing_this_round,code,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,dreamteam_count,ep_next,ep_this,event_points,first_name,form,in_dreamteam,news,news_added,price,photo,points_per_game,removed,last_name,selected_by_percent,special,squad_number,status,team_code,total_points,transfers_in,transfers_in_event,transfers_out,transfers_out_event,value_form,value_season,player_name,region,team_join_date,birth_date,has_temporary_code,opta_code,minutes_played,goals_scored,assists,clean_sheets,goals_conceded,own_goals,penalties_saved,penalties_missed,yellow_cards,red_cards,saves,bonus_points,bonus_points_system,influence,creativity,threat,ict_index,clearances_blocks_interceptions,recoveries,tackles,defensive_contribution,starts,expected_goals,expected_assists,expected_goal_involvements,expected_goals_conceded,influence_rank,influence_rank_type,creativity_rank,creativity_rank_type,threat_rank,threat_rank_type,ict_index_rank,ict_index_rank_type,corners_and_indirect_freekicks_order,corners_and_indirect_freekicks_text,direct_freekicks_order,direct_freekicks_text,penalties_order,penalties_text,expected_goals_per_90,saves_per_90,expected_assists_per_90,expected_goal_involvements_per_90,expected_goals_conceded_per_90,goals_conceded_per_90,now_cost_rank,now_cost_rank_type,form_rank,form_rank_type,points_per_game_rank,points_per_game_rank_type,selected_rank,selected_rank_type,starts_per_90,clean_sheets_per_90,defensive_contribution_per_90,team,team_name_long,position,pos_name_long,goal_involvements,total_points_per_90,goals_scored_per_90,assists_per_90,goal_involvements_per_90,bonus_points_system_per_90,influence_per_90,creativity_per_90,threat_per_90,ict_index_per_90
player_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
7,True,True,NaN,NaN,466075,1,-1,1,-1,2,12.5,14.0,13,Riccardo,13.0,True,,None,5.6,466075.jpg,13.0,False,Calafiori,7.8,False,None,a,3,26,596419,320870,70550,44258,2.3,4.6,Calafiori,106.0,2024-07-29,2002-05-19,False,p466075,134,1,2,2,0,0,0,0,1,0,0,3,71,74.2,23.5,57.0,15.4,4,6,1,5,2,1.3,0.0,1.3,1.0,12,4,87,20,17,3,14,2,NaN,,NaN,,NaN,,0.9,0.0,0.0,0.9,0.7,0.0,119,11,1,1,1,1,55,19,1.3,1.3,3.4,ARS,Arsenal,DEF,Defender,3,17.5,0.7,1.3,2.0,47.7,49.8,15.8,38.3,10.3
8,True,True,NaN,NaN,445122,1,-1,1,-1,1,11.5,13.0,24,Jurriën,12.0,True,,None,5.6,445122.jpg,12.0,False,Timber,6.3,False,None,a,3,24,419240,404659,77313,39721,2.1,4.3,J.Timber,152.0,2023-07-14,2001-06-17,False,p445122,82,2,1,1,0,0,0,0,1,0,0,3,65,98.0,28.8,75.0,20.2,3,2,6,9,1,0.8,0.0,0.9,0.8,1,1,64,14,5,1,3,1,NaN,,NaN,,NaN,,0.9,0.0,0.0,0.9,0.9,0.0,118,10,2,2,3,2,63,22,1.1,1.1,9.9,ARS,Arsenal,DEF,Defender,3,26.3,2.2,1.1,3.3,71.3,107.6,31.6,82.3,22.2
82,True,True,NaN,NaN,437730,1,-1,2,-2,1,10.5,10.5,6,Antoine,10.5,True,,None,7.2,437730.jpg,10.5,False,Semenyo,21.7,False,None,a,91,21,1584223,683190,143555,94796,1.5,2.9,Semenyo,81.0,2023-01-27,2000-01-07,False,p437730,180,2,1,1,4,0,0,0,0,0,0,3,53,86.6,37.3,77.0,20.1,1,8,1,10,2,1.6,0.1,1.7,2.7,7,3,45,37,4,2,4,2,NaN,,NaN,,3.0,,0.8,0.0,0.0,0.8,1.3,2.0,30,17,3,1,4,2,17,6,1.0,0.5,5.0,BOU,Bournemouth,MID,Midfielder,3,10.5,1.0,0.5,1.5,26.5,43.3,18.6,38.5,10.0
661,True,True,NaN,NaN,510663,1,-1,2,-2,0,10.5,10.5,9,Hugo,10.0,True,,None,8.7,510663.jpg,10.0,False,Ekitiké,25.8,False,None,a,14,20,1102885,484142,201892,106933,1.1,2.3,Ekitiké,73.0,2025-07-23,2002-06-20,False,p510663,150,2,1,0,2,0,0,0,0,0,0,5,70,92.6,46.8,60.0,19.9,4,2,0,6,2,1.4,0.1,1.4,2.3,2,1,27,1,14,6,5,2,NaN,,NaN,,NaN,,0.8,0.0,0.0,0.9,1.4,1.2,9,5,4,1,5,1,10,3,1.2,0.0,3.6,LIV,Liverpool,FWD,Forward,3,12.0,1.2,0.6,1.8,42.0,55.6,28.1,36.0,11.9
205,True,True,NaN,NaN,172567,0,0,0,0,1,8.5,9.0,14,Josh,9.0,True,,None,5.0,172567.jpg,9.0,False,Cullen,1.2,False,None,a,90,18,108117,104463,14794,13669,1.8,3.6,Cullen,104.0,2022-07-12,1996-04-07,False,p172567,180,1,1,1,3,0,0,0,0,0,0,3,70,89.6,76.4,21.0,18.7,7,8,4,19,2,0.1,0.5,0.6,3.1,4,1,6,6,72,41,8,5,1.0,,NaN,,NaN,,0.0,0.0,0.2,0.3,1.5,1.5,241,153,6,2,8,3,171,56,1.0,0.5,9.5,BUR,Burnley,MID,Midfielder,2,9.0,0.5,0.5,1.0,35.0,44.8,38.2,10.5,9.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,True,True,100.0,50.0,492777,0,0,0,0,0,0.5,0.2,0,Conor,0.0,False,,2025-08-10T23:00:06.506922Z,5.0,492777.jpg,0.0,False,Bradley,0.1,False,None,a,14,0,2288,1554,5826,1854,0.0,0.0,Bradley,242.0,2023-09-25,2003-07-09,False,p492777,10,0,0,0,1,0,0,0,1,0,0,0,-7,4.0,1.3,2.0,0.7,1,0,0,1,0,0.0,0.0,0.0,0.2,285,104,266,89,248,77,307,102,NaN,,NaN,,NaN,,0.0,0.0,0.1,0.1,1.4,9.0,305,51,645,226,645,226,476,180,0.0,0.0,9.0,LIV,Liverpool,DEF,Defender,0,0.0,0.0,0.0,0.0,-63.0,36.0,11.7,18.0,6.3
148,True,True,NaN,NaN,231416,-1,1,-1,1,0,-0.5,0.0,0,Ferdi,0.0,False,,None,4.4,231416.jpg,0.0,False,Kadıoğlu,0.2,False,None,a,36,0,1438,484,6116,2631,0.0,0.0,F.Kadıoğlu,219.0,2024-08-27,1999-10-07,False,p231416,44,0,0,0,1,0,0,0,2,0,0,0,-6,0.0,3.5,0.0,0.3,2,2,0,2,0,0.0,0.0,0.0,0.6,451,189,222,67,397,166,328,113,NaN,,NaN,,NaN,,0.0,0.0,0.0,0.0,1.3,2.0,567,143,460,185,460,185,404,151,0.0,0.0,4.1,BHA,Brighton,DEF,Defender,0,0.0,0.0,0.0,0.0,-12.3,0.0,7.2,0.0,0.6
605,True,True,NaN,NaN,214048,-1,1,-1,1,0,0.0,-0.5,0,Maximilian,0.0,False,,None,4.4,214048.jpg,0.0,False,Kilman,0.2,False,None,a,21,0,1564,1167,10217,3444,0.0,0.0,Kilman,241.0,2024-07-05,1997-05-23,False,p214048,180,0,0,0,8,0,0,0,1,0,0,0,-14,31.2,16.5,7.0,5.4,11,3,3,14,2,0.2,0.0,0.2,3.4,111,49,110,28,174,45,133,41,NaN,,NaN,,NaN,,0.1,0.0,0.0,0.1,1.7,4.0,566,142,459,184,459,184,341,122,1.0,0.0,7.0,WHU,West Ham,DEF,Defender,0,0.0,0.0,0.0,0.0,-7.0,15.6,8.2,3.5,2.7
672,True,True,NaN,NaN,551210,-1,1,-1,1,0,0.5,0.5,0,Jorrel,0.0,False,,None,4.9,551210.jpg,0.0,False,Hato,0.3,False,None,a,8,0,3571,1547,12854,6006,0.0,0.0,Hato,152.0,2025-08-03,2006-03-07,False,p551210,21,0,0,0,0,0,0,0,1,0,0,0,-2,1.2,1.0,0.0,0.2,1,1,0,1,0,0.0,0.0,0.0,0.4,320,115,283,100,579,213,336,118,NaN,,NaN,,NaN,,0.0,0.0,0.0,0.0,1.9,0.0,361,63,619,223,619,223,326,119,0.0,0.0,4.3,CHE,Chelsea,DEF,Defender,0,0.0,0.0,0.0,0.0,-8.6,5.1,4.3,0.0,0.9
637,True,True,NaN,NaN,510362,0,0,0,0,0,-1.0,-1.0,-2,Toti,-1.0,False,,None,4.5,510362.jpg,-1.0,False,Gomes,0.1,False,None,a,39,-2,1192,310,3887,2037,-0.2,-0.4,Toti,173.0,2022-01-14,1999-01-16,False,p510362,138,0,0,0,5,0,0,0,0,1,0,0,-9,22.2,11.4,0.0,3.3,8,6,2,10,2,0.0,0.0,0.0,3.2,154,66,157,47,488,199,215,72,NaN,,NaN,,NaN,,0.0,0.0,0.0,0.0,2.1,3.3,487,127,707,234,707,234,424,162,1.3,0.0,6.5,WOL,Wolves,DEF,Defender,0,-1.3,0.0,0.0,0.0,-5.9,14.5,7.4,0.0,2.2

## Player summary
The `.get_player_summary()` method can be used to get a player's past or future fixtures

In [4]:
# get the upcoming fixtures for a player
player_fx = data.get_player_summary(355, "fixtures")
player_fx.head()

Fetching
...
DONE!

   team  difficulty
gw
3   NEW           3
4   FUL           3
5   WOL           3
6   BOU           3
7   TOT           3

We can apply some styling to the result above to get a more graphical representation of the upcoming fixtures' difficulty

In [5]:
def style_background_player_fdr(cell_value):
    bg = "background-color:"

    if cell_value == 1:
        return f"{bg} darkgreen;"
    elif cell_value == 2:
        return f"{bg} green;"
    elif cell_value == 3:
        return f"{bg} grey;"
    elif cell_value == 4:
        return f"{bg} orange;"
    elif cell_value == 5:
        return f"{bg} darkred;"
    else:
        return ""


# ToDo: make this part of the package
player_fx.head(10).T.style.map(style_background_player_fdr)

In [6]:
# ToDo: handle case when there are no previous fixtures
player_id = 355
data.get_player_summary(player_id, "history")

Fetching
...
DONE!

,opponent,score,total_points,starts,minutes_played,goals_scored,assists,expected_goals,expected_assists,expected_goal_involvements,clean_sheets,goals_conceded,expected_goals_conceded,own_goals,penalties_saved,penalties_missed,yellow_cards,red_cards,saves,bonus_points,bonus_points_system,influence,creativity,threat,ict_index,net_transfers,selected_by,price
gw,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,EVE (H),1 - 0,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,9774,5.0
2,ARS (A),5 - 0,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,-1633,10276,5.0

## Fixtures
Try to create a fixtures matrix, showing each team's upcoming fixtures and their difficulty

In [7]:
fx = data.get_fixtures_matrix()
fx

,3,4,5,6,7,8,9,10,11
team_home,,,,,,,,,
TOT,BOU (H) 3,WHU (A) 2,BHA (A) 3,WOL (H) 2,LEE (A) 2,AVL (H) 3,EVE (A) 3,CHE (H) 3,MUN (H) 3
NFO,WHU (H) 2,ARS (A) 4,BUR (A) 2,SUN (H) 2,NEW (A) 4,CHE (H) 3,BOU (A) 3,MUN (H) 3,LEE (H) 2
LEE,NEW (H) 3,FUL (A) 3,WOL (A) 3,BOU (H) 3,TOT (H) 3,BUR (A) 2,WHU (H) 2,BHA (A) 3,NFO (A) 3
NEW,LEE (A) 2,WOL (H) 2,BOU (A) 3,ARS (H) 4,NFO (H) 3,BHA (A) 3,FUL (H) 3,WHU (A) 2,BRE (A) 3
WOL,EVE (H) 2,NEW (A) 4,LEE (H) 2,TOT (A) 3,BHA (H) 3,SUN (A) 2,BUR (H) 2,FUL (A) 3,CHE (A) 4
WHU,NFO (A) 3,TOT (H) 3,CRY (H) 3,EVE (A) 3,ARS (A) 4,BRE (H) 3,LEE (A) 2,NEW (H) 3,BUR (H) 2
CHE,FUL (H) 3,BRE (A) 3,MUN (A) 3,BHA (H) 3,LIV (H) 4,NFO (A) 3,SUN (H) 2,TOT (A) 3,WOL (H) 2
BRE,SUN (A) 2,CHE (H) 3,FUL (A) 3,MUN (H) 3,MCI (H) 4,WHU (A) 2,LIV (H) 4,CRY (A) 3,NEW (H) 3
SUN,BRE (H) 3,CRY (A) 3,AVL (H) 3,NFO (A) 3,MUN (A) 3,WOL (H) 2,CHE (A) 4,EVE (H) 2,ARS (H) 4
CRY,AVL (A) 4,SUN (H) 2,WHU (A) 2,LIV (H) 4,EVE (A) 3,BOU (H) 3,ARS (A) 4,BRE (H) 3,BHA (H) 3
BHA,MCI (H) 4,BOU (A) 3,TOT (H) 3,CHE (A) 4,WOL (A) 3,NEW (H) 3,MUN (A) 3,LEE (H) 2,CRY (A) 3
EVE,WOL (A) 3,AVL (H) 3,LIV (A) 5,WHU (H) 2,CRY (H) 3,MCI (A) 4,TOT (H) 3,SUN (A) 2,FUL (H) 3
MUN,BUR (H) 2,MCI (A) 4,CHE (H) 3,BRE (A) 3,SUN (H) 2,LIV (A) 5,BHA (H) 3,NFO (A) 3,TOT (A) 3
BOU,TOT (A) 3,BHA (H) 3,NEW (H) 3,LEE (A) 2,FUL (H) 3,CRY (A) 3,NFO (H) 3,MCI (A) 4,AVL (A) 4
ARS,LIV (A) 5,NFO (H) 3,MCI (H) 4,NEW (A) 4,WHU (H) 2,FUL (A) 3,CRY (H) 3,BUR (A) 2,SUN (A) 2
AVL,CRY (H) 3,EVE (A) 3,SUN (A) 2,FUL (H) 3,BUR (H) 2,TOT (A) 3,MCI (H) 4,LIV (A) 5,BOU (H) 3
LIV,ARS (H) 4,BUR (A) 2,EVE (H) 2,CRY (A) 3,CHE (A) 4,MUN (H) 3,BRE (A) 3,AVL (H) 3,MCI (A) 4
MCI,BHA (A) 3,MUN (H) 3,ARS (A) 4,BUR (H) 2,BRE (A) 3,EVE (H) 2,AVL (A) 4,BOU (H) 3,LIV (H) 4
FUL,CHE (A) 4,LEE (H) 2,BRE (H) 3,AVL (A) 4,BOU (A) 3,ARS (H) 4,NEW (A) 4,WOL (H) 2,EVE (A) 3
BUR,MUN (A) 3,LIV (H) 4,NFO (H) 3,MCI (A) 4,AVL (A) 4,LEE (H) 2,WOL (A) 3,ARS (H) 4,WHU (A) 2

In [8]:
def style_background_team_fdr(cell_value):
    bg = "background-color:"
    team_str = 0

    if cell_value != "":
        team_str = int(cell_value[-1])

    if team_str == 1:
        return f"{bg} darkgreen;"
    elif team_str == 2:
        return f"{bg} green;"
    elif team_str == 3:
        return f"{bg} grey;"
    elif team_str == 4:
        return f"{bg} orange;"
    elif team_str == 5:
        return f"{bg} darkred;"
    else:
        return ""


fx.style.map(style_background_team_fdr)