# How to access FPL API data
This notebook outlines how to extract data from the FPL API using the `requests` package in Python.

In [1]:
import requests
import time
from pprint import pprint
import pandas as pd
from tqdm.auto import tqdm

tqdm.pandas()

pd.set_option("display.max_columns", None)

## Bootstrap_static
This endpoint returns the data for players, positions and teams. We can inspect the different entities returned by this endpoint using the `pprint()` function with the `depth` parameter set to 1

In [2]:
# base url for all FPL API endpoints
base_url = "https://fantasy.premierleague.com/api/"

# get data from bootstrap-static endpoint
r = requests.get(base_url + "bootstrap-static/").json()

# show the top level fields
pprint(r, indent=2, depth=1, compact=True)

{ 'chips': [...],
  'element_stats': [...],
  'element_types': [...],
  'elements': [...],
  'events': [...],
  'game_config': {...},
  'game_settings': {...},
  'phases': [...],
  'teams': [...],
  'total_players': 11243049}

### Players
Player data can be found in the `elements` entity. The response from the `bootstrap_static` endpoint is in json format, which is essentially just a dictionary of keys and values.   
Therefore, to get the `elements` entity, we can use `r['elements']`

In [3]:
# get player data from 'elements' field
players = r["elements"]

# show data for first player
pprint(players[0])

{'assists': 0,
 'birth_date': '1995-09-15',
 'bonus': 3,
 'bps': 66,
 'can_select': True,
 'can_transact': True,
 'chance_of_playing_next_round': None,
 'chance_of_playing_this_round': None,
 'clean_sheets': 2,
 'clean_sheets_per_90': 1.0,
 'clearances_blocks_interceptions': 1,
 'code': 154561,
 'corners_and_indirect_freekicks_order': None,
 'corners_and_indirect_freekicks_text': '',
 'cost_change_event': 0,
 'cost_change_event_fall': 0,
 'cost_change_start': 0,
 'cost_change_start_fall': 0,
 'creativity': '0.0',
 'creativity_rank': 674,
 'creativity_rank_type': 82,
 'defensive_contribution': 0,
 'defensive_contribution_per_90': 0.0,
 'direct_freekicks_order': None,
 'direct_freekicks_text': '',
 'dreamteam_count': 1,
 'element_type': 1,
 'ep_next': '7.5',
 'ep_this': '9.0',
 'event_points': 6,
 'expected_assists': '0.00',
 'expected_assists_per_90': 0.0,
 'expected_goal_involvements': '0.00',
 'expected_goal_involvements_per_90': 0.0,
 'expected_goals': '0.00',
 'expected_goals_conceded': '1.69',
 'expected_goals_conceded_per_90': 0.84,
 'expected_goals_per_90': 0.0,
 'first_name': 'David',
 'form': '8.0',
 'form_rank': 13,
 'form_rank_type': 3,
 'goals_conceded': 0,
 'goals_conceded_per_90': 0.0,
 'goals_scored': 0,
 'has_temporary_code': False,
 'ict_index': '6.2',
 'ict_index_rank': 108,
 'ict_index_rank_type': 2,
 'id': 1,
 'in_dreamteam': False,
 'influence': '62.6',
 'influence_rank': 21,
 'influence_rank_type': 2,
 'minutes': 180,
 'news': '',
 'news_added': None,
 'now_cost': 55,
 'now_cost_rank': 131,
 'now_cost_rank_type': 3,
 'opta_code': 'p154561',
 'own_goals': 0,
 'penalties_missed': 0,
 'penalties_order': None,
 'penalties_saved': 0,
 'penalties_text': '',
 'photo': '154561.jpg',
 'points_per_game': '8.0',
 'points_per_game_rank': 15,
 'points_per_game_rank_type': 3,
 'recoveries': 16,
 'red_cards': 0,
 'region': 200,
 'removed': False,
 'saves': 8,
 'saves_per_90': 4.0,
 'second_name': 'Raya Martín',
 'selected_by_percent': '21.5',
 'selected_rank': 19,
 'selected_rank_type': 3,
 'special': False,
 'squad_number': None,
 'starts': 2,
 'starts_per_90': 1.0,
 'status': 'a',
 'tackles': 0,
 'team': 1,
 'team_code': 3,
 'team_join_date': '2024-07-04',
 'threat': '0.0',
 'threat_rank': 662,
 'threat_rank_type': 82,
 'total_points': 16,
 'transfers_in': 391309,
 'transfers_in_event': 113970,
 'transfers_out': 165695,
 'transfers_out_event': 107015,
 'value_form': '1.5',
 'value_season': '2.9',
 'web_name': 'Raya',
 'yellow_cards': 1}

### Use pandas for cleaner visualisation
Pandas can easily convert JSON data into a dataframe using the `json_normalize()` function.

In [4]:
# create players dataframe
players = pd.json_normalize(r["elements"])

# show some information about first five players
players[["id", "web_name", "team", "element_type"]].head()

   id      web_name  team  element_type
0   1          Raya     1             1
1   2  Arrizabalaga     1             1
2   3          Hein     1             1
3   4       Setford     1             1
4   5       Gabriel     1             2

### Teams

In [5]:
# create teams dataframe
teams = pd.json_normalize(r["teams"])

teams.head()

,code,draw,form,id,loss,name,played,points,position,short_name,strength,team_division,unavailable,win,strength_overall_home,strength_overall_away,strength_attack_home,strength_attack_away,strength_defence_home,strength_defence_away,pulse_id
0,3,0,None,1,0,Arsenal,0,0,1,ARS,4,None,False,0,1320,1325,1350,1350,1290,1300,1
1,7,0,None,2,0,Aston Villa,0,0,17,AVL,3,None,False,0,1125,1250,1110,1200,1140,1300,2
2,90,0,None,3,0,Burnley,0,0,11,BUR,2,None,False,0,1050,1050,1050,1050,1050,1050,43
3,91,0,None,4,0,Bournemouth,0,0,9,BOU,3,None,False,0,1150,1180,1100,1160,1200,1200,127
4,94,0,None,5,0,Brentford,0,0,10,BRE,3,None,False,0,1120,1185,1080,1080,1160,1290,130

### Player positions

In [6]:
# get position information from 'element_types' field
positions = pd.json_normalize(r["element_types"])

positions.head()

,id,plural_name,plural_name_short,singular_name,singular_name_short,squad_select,squad_min_select,squad_max_select,squad_min_play,squad_max_play,ui_shirt_specific,sub_positions_locked,element_count
0,1,Goalkeepers,GKP,Goalkeeper,GKP,2,None,None,1,1,True,[12],82
1,2,Defenders,DEF,Defender,DEF,5,None,None,3,5,False,[],234
2,3,Midfielders,MID,Midfielder,MID,5,None,None,2,5,False,[],316
3,4,Forwards,FWD,Forward,FWD,3,None,None,1,3,False,[],75

## Combined dataset

In [7]:
# select columns of interest from players df
df = players[["id", "first_name", "second_name", "web_name", "team", "element_type"]]

# join team name
df = (
    df.merge(
        teams[["id", "name"]], left_on="team", right_on="id", suffixes=["_player", None]
    )
    .drop(
        ["team", "id"],
        axis=1,
        # join player positions
    )
    .merge(
        positions[["id", "singular_name_short"]], left_on="element_type", right_on="id"
    )
    .drop(["element_type", "id"], axis=1)
)

df.rename(
    columns={"id_player": "id", "name": "team_name", "singular_name_short": "position"},
    inplace=True,
)

df.head()

   id first_name            second_name      web_name team_name position
0   1      David            Raya Martín          Raya   Arsenal      GKP
1   2       Kepa  Arrizabalaga Revuelta  Arrizabalaga   Arsenal      GKP
2   3       Karl                   Hein          Hein   Arsenal      GKP
3   4      Tommy                Setford       Setford   Arsenal      GKP
4   5    Gabriel   dos Santos Magalhães       Gabriel   Arsenal      DEF

### Player gameweek history
Individual gameweek scores can be retrieved on a per-player basis

In [8]:
# get data from 'element-summary/{PID}/' endpoint for PID=3
r = requests.get(base_url + "element-summary/3/").json()

# show top-level fields for player summary
pprint(r, depth=1)

{'fixtures': [...], 'history': [...], 'history_past': [...]}

In [9]:
pd.json_normalize(r["history"]).head()

,element,fixture,opponent_team,total_points,was_home,kickoff_time,team_h_score,team_a_score,round,modified,minutes,goals_scored,assists,clean_sheets,goals_conceded,own_goals,penalties_saved,penalties_missed,yellow_cards,red_cards,saves,bonus,bps,influence,creativity,threat,ict_index,clearances_blocks_interceptions,recoveries,tackles,defensive_contribution,starts,expected_goals,expected_assists,expected_goal_involvements,expected_goals_conceded,value,transfers_balance,selected,transfers_in,transfers_out
0,3,9,14,0,False,2025-08-17T15:30:00Z,0,1,1,False,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.00,0.00,0.00,0.00,40,0,55400,0,0
1,3,11,11,0,True,2025-08-23T16:30:00Z,5,0,2,False,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.00,0.00,0.00,0.00,40,-1321,64836,3835,5156

If we create a function to get gameweek history for a player, we can then apply this function across all the rows of the `players` dataframe

In [10]:
def get_gameweek_history(player_id):
    """get all gameweek info for a given player_id"""

    # send GET request to
    # https://fantasy.premierleague.com/api/element-summary/{PID}/
    r = requests.get(base_url + "element-summary/" + str(player_id) + "/").json()

    # extract 'history' data from response into dataframe
    df = pd.json_normalize(r["history"])

    # avoid getting rate limited
    time.sleep(0.3)

    return df


# show player #4's gameweek history
get_gameweek_history(player_id=3)[
    ["round", "total_points", "minutes", "goals_scored", "assists"]
].head(10)

   round  total_points  minutes  goals_scored  assists
0      1             0        0             0        0
1      2             0        0             0        0

The same can be done to get past seasons' summaries

In [11]:
def get_season_history(player_id):
    """get all past season info for a given player_id"""

    # send GET request to
    # fantasy.premierleague.com/api/element-summary/{PID}/
    r = requests.get(base_url + "element-summary/" + str(player_id) + "/").json()

    # extract 'history_past' data from response into dataframe
    df = pd.json_normalize(r["history_past"])
    df.insert(0, "id", player_id)

    # avoid getting rate limited
    time.sleep(0.3)

    return df


# show player #3's gameweek history
get_season_history(player_id=3)[
    ["id", "season_name", "total_points", "minutes", "goals_scored", "assists"]
].head(10)

   id season_name  total_points  minutes  goals_scored  assists
0   3     2021/22             0        0             0        0
1   3     2022/23             0        0             0        0
2   3     2023/24             0        0             0        0
3   3     2024/25             0        0             0        0